variables:
  MYSQL_DATABASE: oivindhl
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: '123'

test:
  stage: test
  image: node:latest
  services:
    - mysql:5 # The JS mysql-library does not yet support the newest mysql protocol
  script:
    - cd server npm install
    - cd test && npm test