image: 'node:latest'

variables:
  MYSQL_DATABASE: oivindhl
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: '123'

# Install node libraries
pages:
  script:
  - cd client && npm install
  - ./node_modules/.bin/esdoc -c ../.esdoc.json
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  image: node:latest
  services:
    - mysql:5.7.24 # The JS mysql-library does not yet support the newest mysql protocol
  script:
    - cd server && npm install && npm test